# 出站路由配置，默认本机出站，无需配置
# 是否启用路由，若关闭则默认直连
enable=false

# 路由 流媒体
[[routes]]
rules=[
    "geosite:netflix",
    "domain:netflix.ca",
    "domain:netflix.com",
    "domain:netflix.net",
    "domain:netflixinvestor.com",
    "domain:netflixtechblog.com",
    "domain:nflxext.com",
    "domain:nflximg.com",
    "domain:nflximg.net",
    "domain:nflxsearch.net",
    "domain:nflxso.net",
    "domain:nflxvideo.net",
    "domain:netflixdnstest1.com",
    "domain:netflixdnstest2.com",
    "domain:netflixdnstest3.com",
    "domain:netflixdnstest4.com",
    "domain:netflixdnstest5.com",
    "domain:netflixdnstest6.com",
    "domain:netflixdnstest7.com",
    "domain:netflixdnstest8.com",
    "domain:netflixdnstest9.com",
    "domain:netflixdnstest10.com",
    "domain:wikipedia.org",
    "domain:wikipedia.org.com",
    "domain:tiktok.com",
    "domain:www.tiktok.com",
    "domain:tvb.com",
    "domain:tvb.com.au",
    "domain:tvbanywhere.com",
    "domain:tvbanywhere.com.sg",
    "domain:tvbc.com.cn",
    "domain:tvbeventpower.com.hk",
    "domain:tvbusa.com",
    "domain:tvbweekly.com",
    "domain:tvmedia.net.au",
    "domain:videos-f.jwpsrv.com",
    "domain:bigbigchannel.com.hk",
    "domain:bigbigshop.com",
    "domain:content.jwplatform.com",
    "domain:encoretvb.com",
    "domain:mytvsuper.com",
    "domain:mytvsuperlimited.hb.omtrdc.net",
    "domain:mytvsuperlimited.sc.omtrdc.net",
    "domain:112263.com",
    "domain:callhulu.com",
    "domain:findyourlimits.com",
    "domain:freehulu.com",
    "domain:hooloo.tv",
    "domain:hoolu.com",
    "domain:hoolu.tv",
    "domain:hu1u.com",
    "domain:huloo.cc",
    "domain:huloo.tv",
    "domain:hulu.com",
    "domain:hulu.jp",
    "domain:hulu.tv",
    "domain:hulu.us",
    "domain:huluaction.com",
    "domain:huluad.com",
    "domain:huluapp.com",
    "domain:huluasks.com",
    "domain:hulucall.com",
    "domain:hulufree.com",
    "domain:hulugans.com",
    "domain:hulugermany.com",
    "domain:hulugo.com",
    "domain:huluim.com",
    "domain:huluinstantmessenger.com",
    "domain:huluitaly.com",
    "domain:hulunet.com",
    "domain:hulunetwork.com",
    "domain:huluplus.com",
    "domain:hulupremium.com",
    "domain:hulupurchase.com",
    "domain:huluqa.com",
    "domain:hulurussia.com",
    "domain:huluspain.com",
    "domain:hulusports.com",
    "domain:hulustream.com",
    "domain:huluteam.com",
    "domain:hulutv.com",
    "domain:huluusa.com",
    "domain:joinmaidez.com",
    "domain:mushymush.tv",
    "domain:myhulu.com",
    "domain:originalhulu.com",
    "domain:payhulu.com",
    "domain:registerhulu.com",
    "domain:thehulubraintrust.com",
    "domain:wwwhuluplus.com",
    "domain:nicodic.jp",
    "domain:nicomanga.jp",
    "domain:niconico.com",
    "domain:nicoseiga.jp",
    "domain:nicovideo.jp",
    "domain:nimg.jp",
    "domain:simg.jp",
    "geosite:abema",
    "domain:abema.io",
    "domain:abema.tv",
    "domain:abema-tv.com",
    "domain:adx.promo",
    "domain:ameba.jp",
    "domain:amebame.com",
    "domain:amebaownd.com",
    "domain:amebaowndme.com",
    "domain:ameblo.jp",
    "domain:bucketeer.jp",
    "domain:dokusho-ojikan.jp",
    "domain:hayabusa.dev",
    "domain:hayabusa.io",
    "domain:hayabusa.media",
    "domain:winticket.jp",
    "domain:ds-linear-abematv.akamaized.net",
    "domain:linear-abematv.akamaized.net",
    "domain:ds-vod-abematv.akamaized.net",
    "domain:vod-abematv.akamaized.net",
    "domain:mobile-collector.newrelic.com",
    "domain:abema.adx.promo",
    "domain:dazn-api.com",
    "domain:dazn.com",
    "domain:dazndn.com",
    "domain:indazn.com",
    "domain:indaznlab.com",
    "domain:bahamut.akamaized.net",
    "domain:bahamut.com.tw",
    "domain:gamer.com.tw",
    "domain:gamer-cds.cdn.hinet.net",
    "domain:gamer2-cds.cdn.hinet.net",
    "domain:www.viu.tv",
    "domain:www.viu.com",
    "domain:viu.tv",
    "domain:viu.com",
    "geosite:disney",
    "domain:cinemax.com",
    "domain:forthethrone.com",
    "domain:hbo.com",
    "domain:hboasia.com",
    "domain:hbogo.co.th",
    "domain:hbogo.com",
    "domain:hbogo.eu",
    "domain:hbogoasia.com",
    "domain:hbogoasia.hk",
    "domain:hbogoasia.id",
    "domain:hbogoasia.ph",
    "domain:hbogoasia.sg",
    "domain:hbogoasia.tw",
    "domain:hbomax.com",
    "domain:hbomaxcdn.com",
    "domain:hbonow.com",
    "domain:maxgo.com",
    "domain:yo9.com",
    "domain:bilicomics.com",
    "domain:acg.tv",
    "domain:acgvideo.com",
    "domain:animetamashi.cn",
    "domain:animetamashi.com",
    "domain:anitama.cn",
    "domain:anitama.net",
    "domain:b23.tv",
    "domain:bigfun.cn",
    "domain:bigfunapp.cn",
    "domain:bili22.cn",
    "domain:bili2233.cn",
    "domain:bili23.cn",
    "domain:bili33.cn",
    "domain:biliapi.com",
    "domain:biliapi.net",
    "domain:bilibili.cc",
    "domain:bilibili.cn",
    "domain:bilibili.com",
    "domain:bilibili.net",
    "domain:bilibili.tv",
    "domain:bilibilipay.cn",
    "domain:bilibilipay.com",
    "domain:bilicdn1.com",
    "domain:bilicdn2.com",
    "domain:bilicdn3.com",
    "domain:bilicdn4.com",
    "domain:bilicdn5.com",
    "domain:biligo.com",
    "domain:biliintl.com",
    "domain:bilivideo.cn",
    "domain:bilivideo.com",
    "domain:bilivideo.net",
    "domain:dreamcast.hk",
    "domain:hdslb.com",
    "domain:hdslb.org",
    "domain:im9.com",
    "domain:maoercdn.com",
    "domain:mincdn.com",
    "domain:kktv.com.tw",
    "domain:kktv.me",
    "domain:kk.stream",
    "domain:litv.tv",
    "domain:LiTV.tv",
    "domain:cdn.hinet.net",
    "domain:chocotv.com.tw",
    "domain:line-cdn.net",
    "domain:line-scdn.net",
    "domain:linetv.tw",
    "domain:catchplay.com.tw",
    "domain:catchplay.com",
    "domain:cloudfront.net",
    "domain:akamaized.net",
    "domain:dmm-extension.com",
    "domain:dmm.co.jp",
    "domain:dmm.com",
    "domain:videomarket.jp",
    "domain:p-smith.com",
    "domain:vmdash-cenc.akamaized.net",
    "domain:img.vm-movie.jp",
    "domain:bam.nr-data.net",
    "domain:fod.fujitv.co.jp",
    "domain:fod-sp.fujitv.co.jp",
    "domain:i.fod.fujitv.co.jp",
    "domain:stream.ne.jp",
    "domain:music-book.jp",
    "domain:overseaauth.music-book.jp",
    "domain:radiko.jp",
    "domain:radionikkei.jp",
    "domain:smartstream.ne.jp",
    "domain:telasa.jp",
    "domain:kddi-video.com",
    "domain:videopass.jp",
    "domain:d2lmsumy47c8as.cloudfront.net",
    "domain:content-ause1-ur-discovery1.uplynk.com",
    "domain:disco-api.com",
    "domain:discoveryplus.com",
    "domain:x-default-stgec.uplynk.com",
    "domain:discovery.com",
    "domain:discoveryplus.co.uk",
    "domain:getblueshift.com",
    "domain:litix.io",
    "domain:mobile-collector.newrelic.com",
    "domain:discovery.uplynk.com",
    "domain:espn.co.uk",
    "domain:espn.com",
    "domain:espn.net",
    "domain:espncdn.com",
    "domain:espnqa.com",
    "domain:watchespn.com",
    "domain:espn.hb.omtrdc.net",
    "domain:espndotcom.tt.omtrdc.net",
    "domain:espn.api.edge.bamgrid.com",
    "domain:x-live-fox-stgec.uplynk.com",
    "domain:fox.com",
    "domain:foxdcg.com",
    "domain:theplatform.com",
    "domain:cdn-fox-networks-group-green.akamaized.net",
    "domain:d3cv4a9a9wh0bt.cloudfront.net",
    "domain:foxsports01-i.akamaihd.net",
    "domain:foxsports02-i.akamaihd.net",
    "domain:foxsports03-i.akamaihd.net",
    "domain:www.fubo.tv",
    "domain:fubo.tv",
    "domain:paramountplus.com",
    "domain:cbsi.live.ott.irdeto.com",
    "domain:cbsplaylistserver.aws.syncbak.com",
    "domain:cbsservice.aws.syncbak.com",
    "domain:link.theplatform.com",
    "domain:cbsaavideo.com",
    "domain:cbsi.com",
    "domain:cbsivideo.com",
    "domain:pplusstatic.com",
    "domain:geolocation.onetrust.com",
    "domain:peacocktv.com",
    "domain:peacock.com",
    "domain:starplus.com",
    "domain:starott.com",
    "domain:star.api.edge.bamgrid.com",
    "domain:star.connections.edge.bamgrid.com",
    "domain:star.content.edge.bamgrid.com",
    "domain:star.playback.edge.bamgrid.com",
    "domain:britbox.com",
    "domain:www.britbox.com",
    "domain:britbox.co.uk",
    "domain:fxnow.fxnetworks.com",
    "domain:shudder.com",
    "domain:www.shudder.com",
    "domain:www.tlc.com",
    "domain:tlc.com",
    "domain:go.tlc.com",
    "domain:geolocation.onetrust.com",
    "domain:api.trongrid.io",
    "domain:www.bing.com",
    "domain:bing.com",
    "domain:sydney.bing.com",
    "domain:sydney.vcanbb.chat",
    "domain:bingai.nothingnessvoid.tech",
    "domain:cygames.jp",
    "domain:konosubafd.jp",
    "domain:colorfulpalette.org",
    "domain:cds1.clubdam.com",
    "domain:api.worldflipper.jp",
    "geosite:bbc",
    "www.setantasports.com",
    "setantasports.com",
    "app.setantasports.com",
    "imggaming.com",
    "diceplatform.com",
    "dicelaboratory.com",
    "pndsn.com",
    "imggaming.s3-eu-west-1.amazonaws.com",
    "ux1kpaebv0.execute-api.eu-west-1.amazonaws.com",
    "1ok961aaca.execute-api.eu-west-1.amazonaws.com"
]

[[routes.Outs]] # 路由 1 代理出口 1
listen=""
type="trojan"
server="jp-media-unlock-01.xfx.buzz"
port=33333
password="ad2abc68-8fd3-495b-addc-3434e50622cc"
sni="104.128.94.69" # 证书域名
skip_cert_verify=true # 是否跳过证书验证


# 路由 GPT
[[routes]]
rules=[
    "domain:openai.com",
    "domain:chatgpt.com",
    "domain:chat.openai.com",
    "domain:beta.openai.com",
    "domain:platform.openai.com",
    "domain:auth0.openai.com",
    "domain:auth1.openai.com",
    "domain:auth2.openai.com",
    "domain:api.openai.com",
    "domain:cdn.auth0.com",
    "domain:azureedge.net",
    "domain:sentry.io",
    "domain:azurefd.net",
    "domain:intercomcdn.com",
    "domain:intercom.io",
    "domain:google-analytics.com",
    "domain:identrust.com",
    "domain:challenges.cloudflare.com",
    "domain:ai.com",
    "domain:oaistatic.com",
    "domain:oaiusercontent.com"
]

[[routes.Outs]] # 路由 1 代理出口 1
listen=""
type="trojan"
server="jp-media-unlock-01.xfx.buzz"
port=33333
password="ad2abc68-8fd3-495b-addc-3434e50622cc"
sni="104.128.94.69" # 证书域名
skip_cert_verify=true # 是否跳过证书验证

[[routes.Outs]] # 路由 2 代理出口 2
listen=""  #// 出口网卡 ip，不配置则由系统决定
type="ss"
server="c69s2.jjcruises.com"
port=56206
password="VXdg9CJveqc5qU9Q"
cipher="aes-256-gcm"

# 1新 2美

[[routes.Outs]] # 路由 3 代理出口 3
listen="" // 出口网卡 ip，不配置则由系统决定
type="vmess"
server="c69s4.portablesubmarines.com"
port=56206
uuid="f190e13a-6592-48a6-84b3-89dbf0c67b58"
alter_id=0
network="tcp"    # 可选: tcp ws http h2 grpc
ws_path="/asd"
tls=false
sni="xxx.com" # 证书域名
skip_cert_verify=false # 是否跳过证书验证

# 添加任意个路由...

# 路由 N，最后一个路由兜底，否则无法匹配剩余的域名/IP
[[routes]]
# "*" 表示匹配任何域名/IP
rules=["*"]

# 配置直连出口
[[routes.Outs]]
listen="" #// 出口网卡 ip，不配置则由系统决定
type="direct"